version: '3'

services:
  postgres:
    image: 'postgres:11.2-alpine'
    networks:
      - dev
    container_name: 'movie_voting_postgress'
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    networks:
      - dev
    container_name: 'movie_voting_api'
    depends_on:
      - postgres
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '5000:5000'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    networks:
      - dev
    container_name: 'movie_voting_client'
    depends_on:
      - api
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '80:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:5000

volumes:
  postgres_data:

networks:
  dev:
